### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bmroberts1987**
Stormpath

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks @bmroberts1987 , this looks like the addition of an example profile modification route, correct?  I'd like to update the title and description appropriately (this makes it easier for us to review).  Thanks!

**Comment by rorheden** [comment]
Thank you for for bringing this up! I've just done a rebase instead. Also, the changes from the `feature-change-password-form` branch should be merged into master, and this branch should be closed.

**Comment by rorheden** [comment]
Unfortunately I don't have permissions to do anything to this repo. But waiting for @omgitstom or @robertjd to give me permission.

**Comment by lhazlewood** [comment]
@typerandom you should have perms now

**Comment by rorheden** [comment]
Closing issue since it's no longer needed.

**Pull request closed without merging**
